---
- hosts: kube-master[0]
  gather_facts:  True
  tasks:

  # - name: Build persistent storage spec
  #   template:
  #     src: new_values.yml.j2
  #     dest: /tmp/new_values.yml
  #   when: monitoring_storage_class | length >  0
  # - set_fact:
  #   new_opts: "{% if monitoring_storage_class != '' %} -f /tmp/new_values.yml {% else %} {% endif %}" 

    - name: Copy istio charts to master[0]
      copy:
        src: "./files/{{item}}-{{istio_version}}.tgz" 
        dest: /tmp/
      with_items:
      - istio-init 
      - istio      

    # - name: Update istio helm repo 
    #   shell: "/usr/local/bin/helm repo add istio.io https://storage.googleapis.com/istio-release/releases/{{ istio_version }}/charts/"


    - name: Remove istio charts
      shell: "/usr/local/bin/helm del --purge {{ item }}"
      ignore_errors: True
      with_items:
      - istio-init
      - istio
  
    - name: Install istio
      shell: "/usr/local/bin/helm install /tmp/{{ item.chart_name }}-{{istio_version}}.tgz --name {{ item.rel_name }} --namespace {{ istio_namespace }} --version {{ istio_version }} {% if item.opts is defined %} {{ item.opts }} {% else %} {% endif %}"
      with_items:
      - { rel_name: istio-init, chart_name: istio-init }
      - { rel_name: istio, chart_name: istio, opts: --set tracing.enabled=true --set global.mtls.enabled=true --set grafana.enabled=true --set kiali.enabled=true --set servicegraph.enabled=true }
      register: tiller_ready
      retries: 10
      delay: 60
      until: tiller_ready.rc == 0

    - name: Label namespace, default for automatic sidecar injection 
      shell: "kubectl label namespace default istio-injection=enabled"